map/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('mapapp/', include('mapapp.urls')),
    path('admin/', admin.site.urls),
]

mapapp/urls.py
from django.urls import path

from . import views

app_name = 'mapapp'

urlpatterns = [
    # ex: /mapapp/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /mapapp/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /mapapp/5/results/
    path('<int:pk/results>', views.ResultsView.as_view(), name='results'),
    # ex: /mapapp/5/vote/
    path('<int:question_id/vote/', views.vote, name='vote'),
]

mapapp/models.py
import datetime

from django.db import models
from django.utils import timezone


# class Marker(models.Model):
#     description = models.CharField(max_length=200)
#     # geo-data

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return  self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return  self.choice_text

mapapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'mapapp/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'mapapp/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'mapapp/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form
        return render(request, 'mapapp/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()

        return HttpResponseRedirect(reverse('mapapp:results', args=(question.id,)))


# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     template = loader.get_template('mapapp/index.html')
#     context = {
#         'latest_question_list': latest_question_list,
#     }
#     return render(request, 'mapapp/index.html', context)
#
#
# def detail(request, question_id):
#     question = get_list_or_404(Question, pk=question_id)
#     try:
#         question = Question.objects.get(pk=question_id)
#     except Question.DoesNotExist:
#         raise Http404("Question does not exist")
#     return render(request, 'mapapp/detail.html', {'question': question})
#
#
# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'mapapp/results.html', {'question': question})

mapapp/templates/mapapp/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ eroor_message }}</strong></p>{% endif %}

<form action="{% url 'mapapp:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id
}}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

mapapp/templates/mapapp/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'mapapp:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mapapp/templates/mapapp/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'mapapp:detail' question.id %}">Vote again?</a>